### ISSUE TITLE
The save of the Log event should happen async if the config is there

### ISSUE THREAD

**Issue by cavi21** [goodpeople/weasel#4]
For this the idea is to be able to config *Weasel* to:
 - [ ] handle different job processing queues (Sidekiq, DelayedJob, SuckerPunch, etc)
 - [ ] Should be configurable (and not mandatory)

**Comment by horacio** [comment]
For the first iteration, we'll just use Sidekiq. I'll leave this issue open, and subsequent PRs will have this ID, until we reach completion of all tasks.

**Comment by horacio** [comment]
No. We'll just release this.
